--- #YAML:1.0
name:               Regexp-RegGrp
version:            0.01_01
abstract:           Groups regular expressions
author:
    - Merten Falk <nevesenin@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
resources:
    repository:  http://github.com/nevesenin/regexp-reggrp-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
