---
abstract: 'Groups a regular expressions collection'
author:
  - 'Merten Falk, C<< <nevesenin at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.56
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.56
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Regexp::RegGrp
name: Regexp-RegGrp
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.9
resources:
  bugtracker: http://github.com/nevesenin/regexp-reggrp-perl/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/nevesenin/regexp-reggrp-perl
version: 1.002001
